DATABASE_NAME="hbnb_dev_db"
USER_NAME="hbnb_dev"
USER_PASSWORD="hbnb_dev_pwd"

DATABASE IF NOT EXISTS ${DATABASE_NAME};
CREATE USER IF NOT EXISTS '${USER_NAME}'@'localhost' IDENTIFIED BY '${USER_PASSWORD}';
GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO '${USER_NAME}'@'localhost';
GRANT SELECT ON performance_schema.* TO '${USER_NAME}'@'localhost';
FLUSH PRIVILEGES;
